/**
 * Project Templates Library
 * Pre-configured project scaffolds with best practices
 */

import { FileTreeNode } from './file-tree-generator';

export interface ProjectTemplate {
    name: string;
    description: string;
    type: string;
    files: FileTreeNode;
}

/**
 * React Vite Template - Modern React app with Vite, TypeScript, Tailwind
 */
export const reactViteTemplate: ProjectTemplate = {
    name: 'React Vite Starter',
    description: 'Modern React app with Vite, TypeScript, and Tailwind CSS',
    type: 'react-vite',
    files: {
        'index.html': `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vite + React + TS</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>`,
        'src/main.tsx': `import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);`,
        'src/App.tsx': `import React from 'react';

function App() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="container mx-auto px-4 py-16">
        <h1 className="text-4xl font-bold mb-4">Welcome to Your App</h1>
        <p className="text-muted-foreground">
          Start building amazing things with React + Vite + TypeScript
        </p>
      </div>
    </div>
  );
}

export default App;`,
        'src/index.css': `@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
    --background: 0 0% 100%;
    --foreground: 222.2 84% 4.9%;
    --card: 0 0% 100%;
    --card-foreground: 222.2 84% 4.9%;
    --popover: 0 0% 100%;
    --popover-foreground: 222.2 84% 4.9%;
    --primary: 221.2 83.2% 53.3%;
    --primary-foreground: 210 40% 98%;
    --secondary: 210 40% 96.1%;
    --secondary-foreground: 222.2 47.4% 11.2%;
    --muted: 210 40% 96.1%;
    --muted-foreground: 215.4 16.3% 46.9%;
    --accent: 210 40% 96.1%;
    --accent-foreground: 222.2 47.4% 11.2%;
    --destructive: 0 84.2% 60.2%;
    --destructive-foreground: 210 40% 98%;
    --border: 214.3 31.8% 91.4%;
    --input: 214.3 31.8% 91.4%;
    --ring: 221.2 83.2% 53.3%;
    --radius: 0.5rem;
  }

  .dark {
    --background: 222.2 84% 4.9%;
    --foreground: 210 40% 98%;
    --card: 222.2 84% 4.9%;
    --card-foreground: 210 40% 98%;
    --popover: 222.2 84% 4.9%;
    --popover-foreground: 210 40% 98%;
    --primary: 217.2 91.2% 59.8%;
    --primary-foreground: 222.2 47.4% 11.2%;
    --secondary: 217.2 32.6% 17.5%;
    --secondary-foreground: 210 40% 98%;
    --muted: 217.2 32.6% 17.5%;
    --muted-foreground: 215 20.2% 65.1%;
    --accent: 217.2 32.6% 17.5%;
    --accent-foreground: 210 40% 98%;
    --destructive: 0 62.8% 30.6%;
    --destructive-foreground: 210 40% 98%;
    --border: 217.2 32.6% 17.5%;
    --input: 217.2 32.6% 17.5%;
    --ring: 224.3 76.3% 48%;
  }
}

@layer base {
  * {
    @apply border-border;
  }
  body {
    @apply bg-background text-foreground;
    font-feature-settings: "rlig" 1, "calt" 1;
  }
}`,
        'src/vite-env.d.ts': `/// <reference types="vite/client" />`,
    },
};

/**
 * Next.js App Router Template
 */
export const nextjsTemplate: ProjectTemplate = {
    name: 'Next.js App Router',
    description: 'Full-stack Next.js app with App Router, TypeScript, and Tailwind',
    type: 'nextjs-app',
    files: {
        'next.config.js': `/** @type {import('next').NextConfig} */
const nextConfig = {};

export default nextConfig;`,
        'app/layout.tsx': `import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Next.js App',
  description: 'Generated by ExternAI',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}`,
        'app/page.tsx': `export default function Home() {
  return (
    <main className="min-h-screen bg-background text-foreground">
      <div className="container mx-auto px-4 py-16">
        <h1 className="text-4xl font-bold mb-4">Welcome to Next.js</h1>
        <p className="text-muted-foreground">
          Start building amazing full-stack applications
        </p>
      </div>
    </main>
  );
}`,
        'app/globals.css': `@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
    --background: 0 0% 100%;
    --foreground: 222.2 84% 4.9%;
    --card: 0 0% 100%;
    --card-foreground: 222.2 84% 4.9%;
    --popover: 0 0% 100%;
    --popover-foreground: 222.2 84% 4.9%;
    --primary: 221.2 83.2% 53.3%;
    --primary-foreground: 210 40% 98%;
    --secondary: 210 40% 96.1%;
    --secondary-foreground: 222.2 47.4% 11.2%;
    --muted: 210 40% 96.1%;
    --muted-foreground: 215.4 16.3% 46.9%;
    --accent: 210 40% 96.1%;
    --accent-foreground: 222.2 47.4% 11.2%;
    --destructive: 0 84.2% 60.2%;
    --destructive-foreground: 210 40% 98%;
    --border: 214.3 31.8% 91.4%;
    --input: 214.3 31.8% 91.4%;
    --ring: 221.2 83.2% 53.3%;
    --radius: 0.5rem;
  }
}`,
    },
};

/**
 * E-commerce Template
 */
export const ecommerceTemplate: ProjectTemplate = {
    name: 'E-commerce Store',
    description: 'Complete e-commerce app with product catalog, cart, and checkout',
    type: 'ecommerce',
    files: {
        ...reactViteTemplate.files,
        'src/App.tsx': `import React, { useState } from 'react';
import { ShoppingCart } from 'lucide-react';

interface Product {
  id: number;
  name: string;
  price: number;
  image: string;
}

const products: Product[] = [
  { id: 1, name: 'Premium Headphones', price: 299, image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=300&fit=crop' },
  { id: 2, name: 'Wireless Mouse', price: 79, image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&h=300&fit=crop' },
  { id: 3, name: 'Mechanical Keyboard', price: 159, image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400&h=300&fit=crop' },
];

function App() {
  const [cart, setCart] = useState<number[]>([]);

  const addToCart = (productId: number) => {
    setCart([...cart, productId]);
  };

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="bg-card border-b border-border">
        <div className="container mx-auto px-4 py-4 flex justify-between items-center">
          <h1 className="text-2xl font-bold">TechStore</h1>
          <button className="relative p-2">
            <ShoppingCart className="w-6 h-6" />
            {cart.length > 0 && (
              <span className="absolute -top-1 -right-1 bg-primary text-primary-foreground rounded-full w-5 h-5 flex items-center justify-center text-xs">
                {cart.length}
              </span>
            )}
          </button>
        </div>
      </header>

      {/* Product Grid */}
      <main className="container mx-auto px-4 py-8">
        <h2 className="text-3xl font-bold mb-6">Featured Products</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {products.map((product) => (
            <div key={product.id} className="bg-card rounded-lg border border-border overflow-hidden hover:shadow-lg transition-shadow">
              <img src={product.image} alt={product.name} className="w-full h-48 object-cover" />
              <div className="p-4">
                <h3 className="font-semibold text-lg mb-2">{product.name}</h3>
                <p className="text-2xl font-bold text-primary mb-4">\${product.price}</p>
                <button
                  onClick={() => addToCart(product.id)}
                  className="w-full bg-primary text-primary-foreground py-2 rounded-lg hover:opacity-90 transition-opacity"
                >
                  Add to Cart
                </button>
              </div>
            </div>
          ))}
        </div>
      </main>
    </div>
  );
}

export default App;`,
    },
};

/**
 * Dashboard Template
 */
export const dashboardTemplate: ProjectTemplate = {
    name: 'SaaS Dashboard',
    description: 'Professional dashboard with charts, tables, and analytics',
    type: 'dashboard',
    files: {
        ...reactViteTemplate.files,
        'src/App.tsx': `import React from 'react';
import { BarChart3, Users, DollarSign, TrendingUp } from 'lucide-react';

function App() {
  const stats = [
    { label: 'Total Revenue', value: '$45,231', icon: DollarSign, change: '+20.1%' },
    { label: 'Active Users', value: '2,350', icon: Users, change: '+15.3%' },
    { label: 'Sales', value: '573', icon: TrendingUp, change: '+12.5%' },
    { label: 'Conversion', value: '24.5%', icon: BarChart3, change: '+4.3%' },
  ];

  return (
    <div className="min-h-screen bg-background">
      {/* Sidebar */}
      <aside className="fixed left-0 top-0 h-full w-64 bg-card border-r border-border p-4">
        <h2 className="text-xl font-bold mb-6">Dashboard</h2>
        <nav className="space-y-2">
          <a href="#" className="block py-2 px-3 bg-primary text-primary-foreground rounded-lg">Overview</a>
          <a href="#" className="block py-2 px-3 hover:bg-accent rounded-lg">Analytics</a>
          <a href="#" className="block py-2 px-3 hover:bg-accent rounded-lg">Settings</a>
        </nav>
      </aside>

      {/* Main Content */}
      <main className="ml-64 p-8">
        <h1 className="text-3xl font-bold mb-8">Overview</h1>
        
        {/* Stats Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
          {stats.map((stat, idx) => (
            <div key={idx} className="bg-card rounded-lg border border-border p-6">
              <div className="flex items-center justify-between mb-2">
                <stat.icon className="w-8 h-8 text-muted-foreground" />
                <span className="text-sm text-green-600">{stat.change}</span>
              </div>
              <p className="text-sm text-muted-foreground mb-1">{stat.label}</p>
              <p className="text-2xl font-bold">{stat.value}</p>
            </div>
          ))}
        </div>

        {/* Chart Section */}
        <div className="bg-card rounded-lg border border-border p-6">
          <h3 className="text-xl font-semibold mb-4">Revenue Overview</h3>
          <div className="h-64 flex items-end justify-around gap-2">
            {[40, 70, 50, 80, 65, 90, 75].map((height, idx) => (
              <div key={idx} className="flex-1 bg-primary rounded-t" style={{ height: \`\${height}%\` }} />
            ))}
          </div>
        </div>
      </main>
    </div>
  );
}

export default App;`,
    },
};

/**
 * Get template by project type
 */
export function getTemplateByType(type: string): ProjectTemplate | null {
    switch (type) {
        case 'react-vite':
            return reactViteTemplate;
        case 'nextjs-app':
            return nextjsTemplate;
        case 'ecommerce':
            return ecommerceTemplate;
        case 'dashboard':
            return dashboardTemplate;
        default:
            return null;
    }
}

/**
 * List all available templates
 */
export function getAllTemplates(): ProjectTemplate[] {
    return [
        reactViteTemplate,
        nextjsTemplate,
        ecommerceTemplate,
        dashboardTemplate,
    ];
}
